/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ListTouristRequest {
  limit?: number;
  offset?: number;
}

export interface UpsertTouristRequest {
  email: string;
  fullName: string;
  password: string;
}
