/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface InsertTripRequest {
  destination: string;
  endDate: string;
  startDate: string;
  userId: string;
}

export interface ListTripRequest {
  limit?: number;
  offset?: number;
}

export interface UpdateTripRequest {
  destination: string;
  endDate: string;
  startDate: string;
  tripId: string;
}
