/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface UpsertTripRequest {
  destination: string;
  endDate: Date;
  startDate: Date;
  tripId?: string;
  userId?: string;
}
